### ISSUE TITLE
Type-safe "restrict" using RowLacks?

### ISSUE THREAD

**Issue by chexxor** [LightAndLight/purescript-records#1]
In the readme, you say "These operations are actually unsafe because Purescript allows duplicate record labels. It needs a way to say that a row lacks a certain label."

Have you seen `RowLacks` in [`Type.Row` module](https://github.com/purescript/purescript-typelevel-prelude/blob/master/src/Type/Row.purs)? Liam wrote a [blog](https://liamgoodacre.github.io/purescript/2017/05/27/row-lacks.html) to introduce it.

Perhaps you could use this to fix the type of `restrict`:

```
foreign import restrict
  :: forall label a tail result
   . IsSymbol label
  => RowCons label a tail result
  => SProxy label
  => RowLacks label tail
  -> Record result
  -> Record tail
```

**Comment by LightAndLight** [comment]
Yeah I have seen it, thanks. I will probably delete this repo and make a pull request to https://github.com/doolse/purescript-records instead

**Comment by chexxor** [comment]
:+1:
